spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sgc_velare?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:BkW!uAPA5wg09s8xcAvE}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:minha-chave-secreta-super-segura-para-o-sgc-velare}
  expiration: 3600000